// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ZhongCaoCommunity$Type } from "./ZhongCaoCommunity";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ZhongCaoCommunity"]: ZhongCaoCommunity$Type;
    ["contracts/ZhongCaoCommunity.sol:ZhongCaoCommunity"]: ZhongCaoCommunity$Type;
  }

  interface ContractTypesMap {
    ["ZhongCaoCommunity"]: GetContractReturnType<ZhongCaoCommunity$Type["abi"]>;
    ["contracts/ZhongCaoCommunity.sol:ZhongCaoCommunity"]: GetContractReturnType<ZhongCaoCommunity$Type["abi"]>;
  }
}
